spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/democicd_pg
    username: ttsk
    password: ttsk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: democicd


server:
  port: 8081