name: Java CI with SonarCloud

on:
  push:
    branches: ["master"]       # анализ при пуше в main/master
  pull_request:                # анализ при открытии/обновлении PR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Установка JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Сборка проекта и тесты
      - name: Build with Maven
        run: mvn clean verify --batch-mode

      # 4. Jacoco coverage report (будет автоматически собираться благодаря плагину в pom.xml)
      # нет отдельного шага, так как плагин Jacoco уже настроен в pom.xml

      # 5. SonarCloud analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: jeellyyjoo            # ваш SonarCloud organization
          projectKey: jeellyyjoo_democicd     # ваш ключ проекта на SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
